"""
google_auth_service.py
======================
خدمة تسجيل الدخول التفاعلي والتلقائي لحساب Google/YouTube عبر متصفح Chromium / Chrome.
تعمل على السيرفر مع شاشة تحكم حية (Interactive Remote Browser) لاستخراج الكوكيز
مباشرةً من عنوان IP السيرفر (IPv4/IPv6) وتفادي الحظر.

المزايا المتقدمة لتجاوز كشف البوت (Anti-Detection & Stealth):
1. استخدام launch_persistent_context مع ملف تعريف ثابت (.browser_profile) لتفادي وضع التخفي الآلي.
2. تعطيل أعلام الأتمتة بالكامل عبر ignore_default_args=['--enable-automation'].
3. تعطيل مؤشرات التحكم الآلي عبر --disable-blink-features=AutomationControlled.
4. دعم قناة Google Chrome الرسمية (channel="chrome") عند توفرها لتجاوز كشف "المتصفح غير آمن".
5. دعم Xvfb تلقائياً على خوادم لينكس/Docker.
6. واجهة تحكم تفاعلية متكاملة (نقر، كتابة، تنقل حر بين YouTube ودخول Google و SSO).
"""

import os
import sys
import asyncio
import logging
import time
import base64
import subprocess
import shutil
from typing import Dict, Any, Optional

logger = logging.getLogger("google_auth_service")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
COOKIES_FILE = os.path.join(BASE_DIR, "cookies.txt")
RUNTIME_COOKIES_FILE = os.path.join(BASE_DIR, "cookies_runtime.txt")
BROWSER_PROFILE_DIR = os.path.join(BASE_DIR, ".browser_profile")

# حالة الجلسة
_auth_session: Dict[str, Any] = {
    "status": "idle",          # idle | running | waiting_login | extracting | done | error | timeout
    "started_at": None,
    "finished_at": None,
    "message": "",
    "cookies_count": 0,
    "current_url": "",
    "page_title": "",
    "error": None,
}
_auth_lock = asyncio.Lock()

# مراجع المتصفح النشط
_active_context = None
_active_page = None
_active_pw = None
_xvfb_process = None


def _ensure_x_server():
    """
    التأكد من توفر خادم X على أنظمة لينكس.
    إذا لم يكن DISPLAY مضبوطاً، يحاول تشغيل Xvfb في الخلفية على الشاشة :99.
    """
    global _xvfb_process
    if sys.platform.startswith("linux"):
        display = os.environ.get("DISPLAY")
        if not display:
            xvfb_path = shutil.which("Xvfb")
            if xvfb_path:
                try:
                    logger.info("Starting virtual X server (Xvfb) on display :99...")
                    _xvfb_process = subprocess.Popen(
                        ["Xvfb", ":99", "-screen", "0", "1280x800x24", "-nolisten", "tcp"],
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                    os.environ["DISPLAY"] = ":99"
                    time.sleep(0.5)
                    logger.info("Xvfb started successfully on :99")
                except Exception as e:
                    logger.warning(f"Failed to start Xvfb: {e}")
            else:
                logger.warning("Xvfb binary not found in PATH. Browser may need headless mode.")


def get_auth_session_status() -> Dict[str, Any]:
    """إرجاع حالة جلسة المصادقة الحالية."""
    return dict(_auth_session)


def _update_session(**kwargs):
    _auth_session.update(kwargs)


def _cookies_to_netscape(cookies: list) -> str:
    """تحويل كوكيز Playwright إلى صيغة Netscape HTTP Cookie File."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by Google Auth Service", ""]
    for c in cookies:
        domain = c.get("domain", "")
        domain_flag = "FALSE" if domain and not domain.startswith(".") else "TRUE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = int(c.get("expires", 0))
        if expires < 0:
            expires = 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{domain_flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def _is_youtube_authenticated(cookies: list) -> bool:
    """التحقق من وجود كوكيز المصادقة الأساسية لحساب Google/YouTube."""
    auth_cookies = {"SID", "SSID", "HSID", "LOGIN_INFO", "SAPISID", "__Secure-1PSID", "__Secure-3PSID"}
    found = {c["name"] for c in cookies if c["name"] in auth_cookies}
    return len(found) >= 2


async def _save_extracted_cookies(cookies: list) -> int:
    """حفظ الكوكيز في ملف cookies.txt و cookies_runtime.txt وتحديث الجلسة."""
    netscape_content = _cookies_to_netscape(cookies)
    with open(COOKIES_FILE, "w", encoding="utf-8") as f:
        f.write(netscape_content)
    with open(RUNTIME_COOKIES_FILE, "w", encoding="utf-8") as f:
        f.write(netscape_content)

    auth_cookie_names = [c["name"] for c in cookies if c["name"] in {"SID", "SSID", "HSID", "LOGIN_INFO", "SAPISID", "__Secure-1PSID", "__Secure-3PSID"}]
    _update_session(
        status="done",
        finished_at=time.time(),
        cookies_count=len(cookies),
        message=f"تم استخراج {len(cookies)} كوكي وحفظها بنجاح! المفاتيح: {', '.join(auth_cookie_names[:4])}",
        error=None,
    )
    logger.info(f"Cookies saved: {len(cookies)} cookies → {COOKIES_FILE}")
    return len(cookies)


async def start_google_login_session(
    timeout_minutes: int = 15,
    headless: Optional[bool] = None,
    target_url: str = "https://accounts.google.com/ServiceLogin?service=youtube&hl=ar"
) -> Dict[str, Any]:
    """
    بدء جلسة تسجيل الدخول التفاعلية لـ Google.
    - على ويندوز: يفتح متصفح مستمر على سطح المكتب + بث في لوحة التحكم.
    - على لينكس/سيرفر: يستخدم Xvfb لفتح متصفح حقيقي مع ملف تعريف دائم لتجاوز كشف "غير آمن".
    """
    global _auth_session

    async with _auth_lock:
        if _auth_session["status"] in ("running", "waiting_login", "extracting"):
            return {
                "success": False,
                "message": "جلسة تسجيل دخول أخرى جارية بالفعل. يُرجى استخدامها أو إلغاؤها.",
                "session": get_auth_session_status()
            }

        _update_session(
            status="running",
            started_at=time.time(),
            finished_at=None,
            message="جاري تجهيز المتصفح ومضادات كشف البوت...",
            cookies_count=0,
            current_url="",
            page_title="",
            error=None,
        )

    # تشغيل المهمة في الخلفية
    asyncio.create_task(_run_login_session(timeout_minutes, headless, target_url))

    return {
        "success": True,
        "message": "تم بدء جلسة تسجيل الدخول. يمكنك التفاعل مع المتصفح من النافذة الآن.",
        "session": get_auth_session_status()
    }


async def _run_login_session(timeout_minutes: int, headless_override: Optional[bool], target_url: str):
    """المنطق الفعلي لتشغيل متصفح Playwright ومراقبته مع تطبيق أحدث معايير التخفي (Stealth)."""
    global _active_context, _active_page, _active_pw

    try:
        from playwright.async_api import async_playwright
    except ImportError:
        _update_session(
            status="error",
            finished_at=time.time(),
            error="مكتبة Playwright غير مثبتة. شغّل: pip install playwright && playwright install chromium",
            message="خطأ: مكتبة Playwright غير متوفرة."
        )
        return

    # التأكد من خادم Xvfb على لينكس
    _ensure_x_server()

    # تحديد وضع التشغيل (Headless أو Headed)
    if headless_override is not None:
        use_headless = headless_override
    else:
        # إذا كنا على لينكس ولا يوجد DISPLAY ولا Xvfb، نضطر لوضع headless لتفادي الانهيار
        if sys.platform.startswith("linux") and not os.environ.get("DISPLAY"):
            use_headless = True
        else:
            use_headless = False

    pw = None
    context = None
    page = None

    try:
        pw = await async_playwright().start()
        _active_pw = pw

        _update_session(message="جاري فتح متصفح التخفي المستمر...")

        # مجلد البروفايل الدائم لتجنب اعتبار الجلسة مؤقتة/بوت من قِبل جوجل
        os.makedirs(BROWSER_PROFILE_DIR, exist_ok=True)

        launch_args = [
            "--no-sandbox",
            "--disable-setuid-sandbox",
            "--disable-blink-features=AutomationControlled",
            "--disable-infobars",
            "--disable-dev-shm-usage",
            "--disable-features=IsolateOrigins,site-per-process",
            "--window-size=1280,800",
            "--lang=ar-EG,ar",
        ]

        # محاولة فتح Chrome الحقيقي أولاً إذا كان مثبتاً، أو Chromium الافتراضي
        # هذا يحل مشكلة Google: "قد يكون هذا المتصفح أو التطبيق غير آمن"
        context = None
        for channel in ("chrome", None):
            try:
                launch_kwargs = {
                    "user_data_dir": BROWSER_PROFILE_DIR,
                    "headless": use_headless,
                    "ignore_default_args": ["--enable-automation"],
                    "args": launch_args,
                    "viewport": {"width": 1280, "height": 800},
                    "locale": "ar-EG",
                }
                if channel:
                    launch_kwargs["channel"] = channel

                context = await pw.chromium.launch_persistent_context(**launch_kwargs)
                logger.info(f"Launched persistent context successfully (channel={channel}, headless={use_headless})")
                break
            except Exception as ch_err:
                logger.info(f"Launch with channel={channel} not available: {ch_err}")
                continue

        if not context:
            # إذا فشل كل شيء، نحاول وضع headless=True مع Chromium
            context = await pw.chromium.launch_persistent_context(
                user_data_dir=BROWSER_PROFILE_DIR,
                headless=True,
                ignore_default_args=["--enable-automation"],
                args=launch_args,
                viewport={"width": 1280, "height": 800},
                locale="ar-EG",
            )

        _active_context = context

        # أخذ الصفحة الأولى أو إنشاء صفحة جديدة
        page = context.pages[0] if context.pages else await context.new_page()
        _active_page = page

        _update_session(
            status="waiting_login",
            message=f"المتصفح جاهز في النافذة التفاعلية. (المهلة: {timeout_minutes} دقيقة)",
            current_url=target_url,
        )

        # تحميل صفحة تسجيل الدخول
        try:
            await page.goto(target_url, wait_until="domcontentloaded", timeout=40000)
        except Exception as nav_e:
            logger.warning(f"Navigation warning: {nav_e}")

        # حلقة فحص دورية لاكتشاف إتمام تسجيل الدخول تلقائياً
        deadline = time.time() + (timeout_minutes * 60)
        authenticated = False

        while time.time() < deadline:
            if _auth_session["status"] in ("idle", "done", "error"):
                return

            await asyncio.sleep(2)

            try:
                if page.is_closed():
                    break

                curr_url = page.url
                curr_title = await page.title()
                _update_session(current_url=curr_url, page_title=curr_title)

                cookies = await context.cookies()
                if _is_youtube_authenticated(cookies):
                    authenticated = True
                    logger.info(f"Authentication detected! Cookies count: {len(cookies)}")
                    break

                remaining = int(deadline - time.time())
                mins, secs = divmod(remaining, 60)
                _update_session(
                    message=f"في انتظار إتمام تسجيل الدخول... (متبقي {mins}:{secs:02d})"
                )

            except Exception as e:
                logger.debug(f"Check loop error: {e}")
                continue

        if _auth_session["status"] == "done":
            return

        if authenticated:
            _update_session(status="extracting", message="تم كشف الجلسة! جاري استخراج وحفظ الكوكيز...")
            await asyncio.sleep(2)
            all_cookies = await context.cookies()
            await _save_extracted_cookies(all_cookies)
        else:
            if _auth_session["status"] not in ("done", "idle"):
                _update_session(
                    status="timeout",
                    finished_at=time.time(),
                    error="انتهت مهلة تسجيل الدخول. يُرجى إعادة المحاولة.",
                    message="انتهت المهلة قبل إتمام تسجيل الدخول."
                )

    except Exception as e:
        logger.error(f"Login session execution error: {e}", exc_info=True)
        _update_session(
            status="error",
            finished_at=time.time(),
            error=str(e),
            message=f"خطأ في جلسة تسجيل الدخول: {str(e)}"
        )
    finally:
        await _cleanup_browser_resources()


async def _cleanup_browser_resources():
    """تنظيف وإغلاق موارد المتصفح بأمان."""
    global _active_context, _active_page, _active_pw
    try:
        if _active_page and not _active_page.is_closed():
            await _active_page.close()
    except Exception:
        pass
    try:
        if _active_context:
            await _active_context.close()
    except Exception:
        pass
    try:
        if _active_pw:
            await _active_pw.stop()
    except Exception:
        pass

    _active_page = None
    _active_context = None
    _active_pw = None


# =========================================================================
# أدوات التفاعل المباشر مع المتصفح (Interactive Remote Browser API)
# =========================================================================

async def capture_browser_screenshot() -> Dict[str, Any]:
    """التقاط لقطة شاشة سريعة من المتصفح النشط كـ Base64 JPEG."""
    global _active_page
    if not _active_page or _active_page.is_closed():
        return {
            "success": False,
            "message": "لا يوجد متصفح نشط حالياً.",
            "status": _auth_session["status"]
        }

    try:
        img_bytes = await _active_page.screenshot(type="jpeg", quality=65)
        b64 = base64.b64encode(img_bytes).decode("ascii")
        url = _active_page.url
        title = await _active_page.title()
        return {
            "success": True,
            "image": f"data:image/jpeg;base64,{b64}",
            "url": url,
            "title": title,
            "status": _auth_session["status"],
            "message": _auth_session.get("message", "")
        }
    except Exception as e:
        return {"success": False, "error": str(e), "status": _auth_session["status"]}


async def browser_mouse_click(x: int, y: int) -> Dict[str, Any]:
    """إرسال نقرة ماوس إلى إحداثيات محددة في صفحة المتصفح."""
    global _active_page
    if not _active_page or _active_page.is_closed():
        return {"success": False, "message": "لا يوجد متصفح نشط."}

    try:
        await _active_page.mouse.click(x, y)
        await asyncio.sleep(0.4)
        return await capture_browser_screenshot()
    except Exception as e:
        return {"success": False, "error": str(e)}


async def browser_keyboard_type(text: str, press_enter: bool = False) -> Dict[str, Any]:
    """كتابة نص في الحقل النشط بالمتصفح، مع خيار الضغط على Enter."""
    global _active_page
    if not _active_page or _active_page.is_closed():
        return {"success": False, "message": "لا يوجد متصفح نشط."}

    try:
        await _active_page.keyboard.type(text, delay=35)
        if press_enter:
            await asyncio.sleep(0.2)
            await _active_page.keyboard.press("Enter")
        await asyncio.sleep(0.5)
        return await capture_browser_screenshot()
    except Exception as e:
        return {"success": False, "error": str(e)}


async def browser_keyboard_key(key: str) -> Dict[str, Any]:
    """الضغط على مفتاح معين (مثل Enter, Backspace, Tab, ArrowDown)."""
    global _active_page
    if not _active_page or _active_page.is_closed():
        return {"success": False, "message": "لا يوجد متصفح نشط."}

    try:
        await _active_page.keyboard.press(key)
        await asyncio.sleep(0.4)
        return await capture_browser_screenshot()
    except Exception as e:
        return {"success": False, "error": str(e)}


async def browser_reload_page() -> Dict[str, Any]:
    """إعادة تحميل الصفحة الحالية في المتصفح."""
    global _active_page
    if not _active_page or _active_page.is_closed():
        return {"success": False, "message": "لا يوجد متصفح نشط."}

    try:
        await _active_page.reload(wait_until="domcontentloaded", timeout=20000)
        await asyncio.sleep(0.5)
        return await capture_browser_screenshot()
    except Exception as e:
        return {"success": False, "error": str(e)}


async def browser_navigate_to(url: str) -> Dict[str, Any]:
    """الانتقال لعنوان URL محدد في المتصفح (مثلاً YouTube أو صفحة SSO)."""
    global _active_page
    if not _active_page or _active_page.is_closed():
        return {"success": False, "message": "لا يوجد متصفح نشط."}

    try:
        await _active_page.goto(url, wait_until="domcontentloaded", timeout=30000)
        await asyncio.sleep(0.5)
        return await capture_browser_screenshot()
    except Exception as e:
        return {"success": False, "error": str(e)}


async def browser_manual_extract() -> Dict[str, Any]:
    """استخراج الكوكيز فورياً يدوياً بطلب من المستخدم، وحفظها وإنهاء الجلسة."""
    global _active_context
    if not _active_context:
        return {"success": False, "message": "لا توجد جلسة متصفح نشطة لاستخراج الكوكيز منها."}

    try:
        cookies = await _active_context.cookies()
        if not cookies:
            return {"success": False, "message": "لم يتم العثور على أي كوكيز في المتصفح حتى الآن."}

        count = await _save_extracted_cookies(cookies)
        await _cleanup_browser_resources()
        return {
            "success": True,
            "message": f"تم استخراج {count} كوكي وحفظها بنجاح في ملف cookies.txt!",
            "cookies_count": count
        }
    except Exception as e:
        logger.error(f"Manual extract error: {e}", exc_info=True)
        return {"success": False, "error": str(e)}


async def cancel_auth_session() -> Dict[str, Any]:
    """إلغاء جلسة تسجيل الدخول الحالية فوراً."""
    _update_session(
        status="idle",
        finished_at=time.time(),
        message="تم إلغاء الجلسة وإغلاق المتصفح.",
        error=None
    )
    await _cleanup_browser_resources()
    return {"success": True, "message": "تم إلغاء جلسة تسجيل الدخول بنجاح."}


def is_playwright_available() -> bool:
    """التحقق من تثبيت مكتبة Playwright."""
    try:
        import playwright
        return True
    except ImportError:
        return False


def get_playwright_status() -> Dict[str, Any]:
    """معلومات توفر Playwright وخادم Xvfb وحالة الجلسة."""
    available = is_playwright_available()
    has_xvfb = bool(shutil.which("Xvfb")) or sys.platform == "win32"
    return {
        "playwright_installed": available,
        "xvfb_available": has_xvfb,
        "platform": sys.platform,
        "has_display": bool(os.environ.get("DISPLAY")),
        "session": get_auth_session_status()
    }
