"""
google_auth_service.py
======================
خدمة تسجيل الدخول التلقائي لحساب Google/YouTube عبر متصفح Playwright مخفي.
تعمل على السيرفر وتُعيد الكوكيز المستخرجة من نفس الـ IP تلقائياً.

المبدأ:
1. يُشغّل Playwright Chromium headless=False (نافذة مرئية للمستخدم الذي له VNC/RDP)
   أو headless=True مع remote debugging port للتحكم عن بُعد
2. يفتح صفحة تسجيل دخول Google / YouTube
3. بعد اكتمال تسجيل الدخول (كشفناه بوجود كوكيز SID/SSID)، نستخرج الكوكيز
4. نحوّلها لصيغة Netscape ونحفظها في cookies.txt
"""

import os
import asyncio
import logging
import time
import json
from typing import Dict, Any, Optional

logger = logging.getLogger("google_auth_service")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
COOKIES_FILE = os.path.join(BASE_DIR, "cookies.txt")

# حالة جلسة المصادقة الجارية (session state)
_auth_session: Dict[str, Any] = {
    "status": "idle",          # idle | running | waiting_login | extracting | done | error | timeout
    "started_at": None,
    "finished_at": None,
    "message": "",
    "cookies_count": 0,
    "error": None,
    "port": None,              # Chrome remote debugging port
}
_auth_lock = asyncio.Lock()


def get_auth_session_status() -> Dict[str, Any]:
    """إرجاع حالة جلسة المصادقة الحالية."""
    return dict(_auth_session)


def _update_session(**kwargs):
    _auth_session.update(kwargs)


def _cookies_to_netscape(cookies: list) -> str:
    """تحويل كوكيز Playwright إلى صيغة Netscape HTTP Cookie File."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by Google Auth Service", ""]
    for c in cookies:
        domain = c.get("domain", "")
        # إضافة النقطة في بداية النطاق إذا لم تكن موجودة (Netscape format)
        if domain and not domain.startswith("."):
            domain_flag = "FALSE"
        else:
            domain_flag = "TRUE"
        
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = int(c.get("expires", 0))
        if expires < 0:
            expires = 0  # session cookie → treat as no expiry
        name = c.get("name", "")
        value = c.get("value", "")
        
        line = f"{domain}\t{domain_flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}"
        lines.append(line)
    
    return "\n".join(lines) + "\n"


def _is_youtube_authenticated(cookies: list) -> bool:
    """التحقق من وجود كوكيز المصادقة الأساسية لـ Google/YouTube."""
    auth_cookies = {"SID", "SSID", "HSID", "LOGIN_INFO", "SAPISID"}
    found = {c["name"] for c in cookies if c["name"] in auth_cookies}
    return len(found) >= 2  # نحتاج على الأقل 2 كوكيز مصادقة


async def start_google_login_session(
    timeout_minutes: int = 10,
    headless: bool = False,
    target_url: str = "https://accounts.google.com/ServiceLogin?service=youtube"
) -> Dict[str, Any]:
    """
    بدء جلسة تسجيل الدخول لـ Google.
    
    المعاملات:
    - timeout_minutes: الحد الأقصى للانتظار قبل انتهاء المهلة
    - headless: True = متصفح مخفي (يحتاج remote debugging), False = متصفح ظاهر
    - target_url: رابط صفحة تسجيل الدخول
    
    يعمل في الخلفية ويُعيد حالة الجلسة فوراً.
    """
    global _auth_session

    async with _auth_lock:
        if _auth_session["status"] == "running":
            return {"success": False, "message": "جلسة تسجيل دخول أخرى جارية بالفعل. يُرجى الانتظار أو إلغاؤها.", "session": get_auth_session_status()}
        
        _update_session(
            status="running",
            started_at=time.time(),
            finished_at=None,
            message="جاري تهيئة المتصفح...",
            cookies_count=0,
            error=None,
            port=None,
        )

    # تشغيل في الخلفية
    asyncio.create_task(_run_login_session(timeout_minutes, headless, target_url))
    
    return {
        "success": True,
        "message": "تم بدء جلسة تسجيل الدخول. المتصفح يفتح الآن على السيرفر.",
        "session": get_auth_session_status()
    }


async def _run_login_session(timeout_minutes: int, headless: bool, target_url: str):
    """تنفيذ جلسة تسجيل الدخول الفعلية في الخلفية."""
    try:
        from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeout
    except ImportError:
        _update_session(
            status="error",
            finished_at=time.time(),
            error="مكتبة Playwright غير مثبتة. شغّل: pip install playwright && playwright install chromium",
            message="خطأ: مكتبة Playwright غير متوفرة."
        )
        return

    timeout_ms = timeout_minutes * 60 * 1000
    browser = None
    context = None

    try:
        async with async_playwright() as pw:
            _update_session(message="جاري تشغيل متصفح Chromium...")
            
            launch_opts = {
                "headless": headless,
                "args": [
                    "--no-sandbox",
                    "--disable-setuid-sandbox",
                    "--disable-blink-features=AutomationControlled",
                    "--disable-infobars",
                    "--lang=ar-EG,ar",
                ],
            }
            
            # Remote debugging port لـ VNC/noVNC على السيرفر
            if not headless:
                launch_opts["args"].append("--remote-debugging-port=9222")
                _update_session(port=9222)

            browser = await pw.chromium.launch(**launch_opts)
            context = await browser.new_context(
                locale="ar-EG",
                viewport={"width": 1280, "height": 800},
                user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
            )
            
            page = await context.new_page()
            
            # إخفاء علامات الأتمتة
            await page.add_init_script("""
                Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
                Object.defineProperty(navigator, 'plugins', { get: () => [1,2,3,4,5] });
            """)
            
            _update_session(
                status="waiting_login",
                message=f"المتصفح مفتوح. يرجى تسجيل الدخول في النافذة. (المهلة: {timeout_minutes} دقيقة)"
            )
            
            await page.goto(target_url, wait_until="domcontentloaded", timeout=30000)
            logger.info(f"Opened login page: {target_url}")
            
            # الانتظار حتى يكمل المستخدم تسجيل الدخول
            deadline = time.time() + (timeout_minutes * 60)
            authenticated = False
            
            while time.time() < deadline:
                await asyncio.sleep(3)
                
                try:
                    current_url = page.url
                    cookies = await context.cookies()
                    
                    if _is_youtube_authenticated(cookies):
                        authenticated = True
                        logger.info(f"Authentication detected! Cookies count: {len(cookies)}, URL: {current_url}")
                        break
                    
                    # تحديث الرسالة كل 30 ثانية
                    remaining = int(deadline - time.time())
                    mins, secs = divmod(remaining, 60)
                    _update_session(
                        message=f"في انتظار إتمام تسجيل الدخول... (متبقي {mins}:{secs:02d})"
                    )
                    
                except Exception as e:
                    logger.warning(f"Poll error: {e}")
                    continue
            
            if not authenticated:
                _update_session(
                    status="timeout",
                    finished_at=time.time(),
                    error="انتهت مهلة الانتظار. يُرجى إعادة المحاولة.",
                    message="انتهت مهلة تسجيل الدخول."
                )
                return
            
            # استخراج الكوكيز
            _update_session(status="extracting", message="جاري استخراج وحفظ الكوكيز...")
            
            cookies = await context.cookies(["https://www.youtube.com", "https://google.com", "https://accounts.google.com"])
            
            # تحويل وحفظ الكوكيز
            netscape_content = _cookies_to_netscape(cookies)
            
            with open(COOKIES_FILE, "w", encoding="utf-8") as f:
                f.write(netscape_content)
            
            # نسخ احتياطي في cookies_runtime أيضاً
            runtime_file = os.path.join(BASE_DIR, "cookies_runtime.txt")
            with open(runtime_file, "w", encoding="utf-8") as f:
                f.write(netscape_content)
            
            auth_cookie_names = [c["name"] for c in cookies if c["name"] in {"SID", "SSID", "HSID", "LOGIN_INFO", "SAPISID", "__Secure-1PSID", "__Secure-3PSID"}]
            
            _update_session(
                status="done",
                finished_at=time.time(),
                cookies_count=len(cookies),
                message=f"تم استخراج {len(cookies)} كوكي وحفظها بنجاح! مفاتيح المصادقة: {', '.join(auth_cookie_names[:4])}",
                error=None
            )
            
            logger.info(f"Google auth cookies saved: {len(cookies)} cookies → {COOKIES_FILE}")
            
    except Exception as e:
        logger.error(f"Login session error: {e}", exc_info=True)
        _update_session(
            status="error",
            finished_at=time.time(),
            error=str(e),
            message=f"خطأ في جلسة تسجيل الدخول: {str(e)}"
        )
    finally:
        if context:
            try:
                await context.close()
            except Exception:
                pass
        if browser:
            try:
                await browser.close()
            except Exception:
                pass


async def cancel_auth_session() -> Dict[str, Any]:
    """إلغاء جلسة تسجيل الدخول الجارية."""
    if _auth_session["status"] not in ("running", "waiting_login", "extracting"):
        return {"success": False, "message": "لا توجد جلسة نشطة لإلغائها."}
    
    _update_session(
        status="idle",
        finished_at=time.time(),
        message="تم إلغاء الجلسة بواسطة المستخدم.",
        error=None
    )
    return {"success": True, "message": "تم إلغاء جلسة تسجيل الدخول."}


def is_playwright_available() -> bool:
    """التحقق من وجود مكتبة Playwright."""
    try:
        import playwright
        return True
    except ImportError:
        return False


def get_playwright_status() -> Dict[str, Any]:
    """الحصول على حالة Playwright وتوفّر المتصفح."""
    available = is_playwright_available()
    chromium_path = None
    
    if available:
        try:
            from playwright._impl._driver import compute_driver_executable
            import shutil
            chromium_path = shutil.which("chromium") or shutil.which("chromium-browser") or shutil.which("google-chrome")
        except Exception:
            pass
    
    return {
        "playwright_installed": available,
        "chromium_path": chromium_path,
        "session": get_auth_session_status()
    }
